### ISSUE TITLE
Missing Files in process_graph_metrics.py

### ISSUE THREAD

**Issue by SiyuanHuangSJTU** [Xtra-Computing/Cryptocurrency-Graphs-of-graphs#1]
Thank you for sharing your amazing work! I really appreciate the effort you put into this project.

I ran into an issue while trying to execute the `datasets/process_graph_metrics.py` script during the data preparation step. It looks like the script is trying to read the following files:

```python
graphs1 = pd.read_csv(f'../result/{chain}_basic_metrics.csv')
graphs2 = pd.read_csv(f'../result/{chain}_advanced_metrics_labels.csv')
```
However, these files don’t seem to exist. Could you let me know how to generate or obtain these files? Any pointers would be really helpful!

Thanks a lot for your help!

**Comment by BingqiaoL** [comment]
Hi @SiyuanHuangSJTU 

Thanks for the interest!

You can generate these two datasets by running the scripts in the analysis/local_metrics/ directory. Hope this helps!

**Comment by SiyuanHuangSJTU** [comment]
Ok, get it. Thanks a lot for your help!
